# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MorphingGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLoadStartingImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadStartingImage.setGeometry(QtCore.QRect(70, 10, 161, 27))
        self.btnLoadStartingImage.setObjectName("btnLoadStartingImage")
        self.btnLoadEndingImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadEndingImage.setGeometry(QtCore.QRect(550, 10, 161, 27))
        self.btnLoadEndingImage.setObjectName("btnLoadEndingImage")
        self.viewStartingImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.viewStartingImage.setGeometry(QtCore.QRect(70, 40, 291, 221))
        self.viewStartingImage.setObjectName("viewStartingImage")
        self.lblStartingImage = QtWidgets.QLabel(self.centralwidget)
        self.lblStartingImage.setGeometry(QtCore.QRect(150, 260, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblStartingImage.setFont(font)
        self.lblStartingImage.setObjectName("lblStartingImage")
        self.lblEndingImage = QtWidgets.QLabel(self.centralwidget)
        self.lblEndingImage.setGeometry(QtCore.QRect(650, 260, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblEndingImage.setFont(font)
        self.lblEndingImage.setObjectName("lblEndingImage")
        self.chkShowTriangles = QtWidgets.QCheckBox(self.centralwidget)
        self.chkShowTriangles.setGeometry(QtCore.QRect(390, 270, 131, 21))
        self.chkShowTriangles.setObjectName("chkShowTriangles")
        self.sliderAlpha = QtWidgets.QSlider(self.centralwidget)
        self.sliderAlpha.setGeometry(QtCore.QRect(70, 300, 761, 21))
        self.sliderAlpha.setOrientation(QtCore.Qt.Horizontal)
        self.sliderAlpha.setObjectName("sliderAlpha")
        self.lblAlpha = QtWidgets.QLabel(self.centralwidget)
        self.lblAlpha.setGeometry(QtCore.QRect(20, 300, 41, 21))
        self.lblAlpha.setObjectName("lblAlpha")
        self.lblStartingAlpha = QtWidgets.QLabel(self.centralwidget)
        self.lblStartingAlpha.setGeometry(QtCore.QRect(70, 320, 21, 16))
        self.lblStartingAlpha.setObjectName("lblStartingAlpha")
        self.lblEndingAlpha = QtWidgets.QLabel(self.centralwidget)
        self.lblEndingAlpha.setGeometry(QtCore.QRect(800, 320, 21, 16))
        self.lblEndingAlpha.setObjectName("lblEndingAlpha")
        self.txtAlphaValue = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtAlphaValue.setGeometry(QtCore.QRect(840, 300, 61, 21))
        self.txtAlphaValue.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAlphaValue.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAlphaValue.setObjectName("txtAlphaValue")
        self.btnBlendImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnBlendImage.setGeometry(QtCore.QRect(390, 600, 141, 31))
        self.btnBlendImage.setObjectName("btnBlendImage")
        self.lblBlendingResult = QtWidgets.QLabel(self.centralwidget)
        self.lblBlendingResult.setGeometry(QtCore.QRect(400, 560, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblBlendingResult.setFont(font)
        self.lblBlendingResult.setObjectName("lblBlendingResult")
        self.viewEndingImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.viewEndingImage.setGeometry(QtCore.QRect(550, 40, 291, 221))
        self.viewEndingImage.setObjectName("viewEndingImage")
        self.blendImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.blendImage.setGeometry(QtCore.QRect(310, 340, 291, 221))
        self.blendImage.setObjectName("blendImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnLoadStartingImage.setText(_translate("MainWindow", "Load Starting Image ..."))
        self.btnLoadEndingImage.setText(_translate("MainWindow", "Load Ending Image ..."))
        self.lblStartingImage.setText(_translate("MainWindow", "Starting Image"))
        self.lblEndingImage.setText(_translate("MainWindow", "Ending Image"))
        self.chkShowTriangles.setText(_translate("MainWindow", "Show Triangles"))
        self.lblAlpha.setText(_translate("MainWindow", "Alpha"))
        self.lblStartingAlpha.setText(_translate("MainWindow", "0.0"))
        self.lblEndingAlpha.setText(_translate("MainWindow", "1.0"))
        self.btnBlendImage.setText(_translate("MainWindow", "Blend"))
        self.lblBlendingResult.setText(_translate("MainWindow", "Blending Result"))

